import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D0D0D',
  },
  clockContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    marginTop: 40,
  },
  timeText: {
    fontSize: 96,
    fontWeight: '200',
    color: '#FFFFFF',
    letterSpacing: -4,
  },
  ampmText: {
    fontSize: 24,
    fontWeight: '400',
    color: '#666666',
    marginLeft: 8,
  },
  dateText: {
    fontSize: 18,
    color: '#666666',
    textAlign: 'center',
    marginTop: 8,
  },
  countdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  countdownIcon: {
    fontSize: 18,
    marginRight: 8,
    opacity: 0.7,
  },
  countdownText: {
    fontSize: 15,
    fontWeight: '300',
    color: '#9999AA',
    letterSpacing: 0.3,
  },
  alarmsContainer: {
    flex: 1,
    marginTop: 24,
    marginHorizontal: -24,
  },
  alarmsList: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
    paddingHorizontal: 24,
  },
  noAlarmsText: {
    fontSize: 16,
    color: '#444444',
    paddingHorizontal: 24,
  },
  alarmItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingLeft: 24,
    paddingRight: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#1A1A1A',
    backgroundColor: '#0D0D0D',
  },
  alarmInfo: {
    flex: 1,
    marginRight: 16,
    overflow: 'visible',
  },
  alarmTime: {
    fontSize: 32,
    fontWeight: '300',
    color: '#FFFFFF',
    textAlign: 'left',
  },
  alarmTimeDisabled: {
    color: '#444444',
  },
  alarmDays: {
    fontSize: 14,
    color: '#666666',
    marginTop: 4,
  },
  alarmDaysDisabled: {
    color: '#333333',
  },
  undoToast: {
    position: 'absolute',
    bottom: 100,
    left: 24,
    right: 24,
    backgroundColor: '#333333',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  undoToastText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  undoButton: {
    color: '#818CF8',
    fontSize: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  tabContent: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 24,
  },
  addButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#818CF8',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#818CF8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addButtonText: {
    fontSize: 28,
    fontWeight: '300',
    color: '#FFFFFF',
    marginTop: -2,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#141414',
    borderTopWidth: 1,
    borderTopColor: '#1F1F1F',
    paddingBottom: Platform.OS === 'ios' ? 34 : 10,
    paddingTop: 10,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tabIcon: {
    fontSize: 20,
    opacity: 0.4,
  },
  tabIconActive: {
    opacity: 1,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: '#555555',
    letterSpacing: 0.2,
  },
  tabLabelActive: {
    color: '#818CF8',
    fontWeight: '600',
  },
  placeholderScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  placeholderIcon: {
    fontSize: 48,
    marginBottom: 20,
    opacity: 0.8,
  },
  placeholderTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  placeholderSubtitle: {
    fontSize: 15,
    color: '#555555',
    textAlign: 'center',
    lineHeight: 22,
  },
  morningContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  morningGreeting: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  morningQuote: {
    fontSize: 16,
    color: '#9999AA',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 48,
  },
  morningButtons: {
    flexDirection: 'row',
    gap: 16,
  },
  morningButton: {
    backgroundColor: 'rgba(129, 140, 248, 0.15)',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(129, 140, 248, 0.3)',
    minWidth: 130,
  },
  morningButtonIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  morningButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#818CF8',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalScroll: {
    marginTop: 100,
  },
  modalContent: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  cancelButton: {
    fontSize: 16,
    color: '#666666',
  },
  saveButton: {
    fontSize: 16,
    fontWeight: '600',
    color: '#818CF8',
  },
  repeatSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  repeatLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
  },
  daysContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#2A2A2A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayButtonSelected: {
    backgroundColor: '#FFFFFF',
  },
  dayText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
  },
  dayTextSelected: {
    color: '#0D0D0D',
  },
  labelSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  labelTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  labelInput: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#FFFFFF',
  },
  snoozeSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  snoozeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  snoozeOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  snoozeOption: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#2A2A2A',
  },
  snoozeOptionSelected: {
    backgroundColor: '#FFFFFF',
  },
  snoozeOptionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },
  snoozeOptionTextSelected: {
    color: '#0D0D0D',
  },
  wakeIntensitySection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  wakeIntensityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  wakeIntensityTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  previewButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#2A2A2A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewButtonIcon: {
    fontSize: 16,
  },
  wakeIntensityOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  wakeIntensityOption: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#2A2A2A',
    alignItems: 'center',
  },
  wakeIntensityOptionSelected: {
    backgroundColor: '#FFFFFF',
  },
  wakeIntensityOptionText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#666666',
  },
  wakeIntensityOptionTextSelected: {
    color: '#0D0D0D',
  },
  soundSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
  },
  soundTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  soundOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  soundOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#2A2A2A',
    gap: 6,
  },
  soundOptionSelected: {
    backgroundColor: '#FFFFFF',
  },
  soundOptionIcon: {
    fontSize: 16,
  },
  soundOptionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },
  soundOptionTextSelected: {
    color: '#0D0D0D',
  },
  dismissTypeSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
  },
  dismissTypeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  dismissTypeOptions: {
    gap: 12,
  },
  dismissTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#2A2A2A',
    gap: 14,
  },
  dismissTypeOptionSelected: {
    backgroundColor: '#FFFFFF',
  },
  dismissTypeIcon: {
    fontSize: 24,
  },
  dismissTypeTextContainer: {
    flex: 1,
  },
  dismissTypeLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  dismissTypeLabelSelected: {
    color: '#0D0D0D',
  },
  dismissTypeDescription: {
    fontSize: 13,
    color: '#666666',
  },
  dismissTypeDescriptionSelected: {
    color: '#444444',
  },
  missionsSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#818CF8',
    marginTop: 16,
    marginBottom: 4,
  },
  missionsHint: {
    fontSize: 12,
    color: '#555555',
    marginBottom: 12,
  },
  // Alarm Screen Styles
  alarmScreen: {
    flex: 1,
    backgroundColor: '#0D0D0D',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  alarmScreenTime: {
    fontSize: 72,
    fontWeight: '200',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  alarmScreenLabel: {
    fontSize: 24,
    color: '#666666',
    marginBottom: 60,
  },
  mathScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  mathContent: {
    width: '100%',
    alignItems: 'center',
  },
  mathPrompt: {
    fontSize: 18,
    fontWeight: '300',
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 32,
    letterSpacing: 0.5,
  },
  mathProblemText: {
    fontSize: 48,
    fontWeight: '300',
    color: '#FFFFFF',
    marginBottom: 40,
  },
  mathInputField: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 18,
    fontSize: 32,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  mathInputFieldWrong: {
    borderColor: '#F87171',
    backgroundColor: 'rgba(248, 113, 113, 0.1)',
  },
  mathSubmitButton: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  mathSubmitButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  mathCompleteContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mathCompleteText: {
    fontSize: 32,
    fontWeight: '300',
    color: '#4ADE80',
    letterSpacing: 1,
  },
  shakeScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  shakeContent: {
    width: '100%',
    alignItems: 'center',
  },
  shakePrompt: {
    fontSize: 18,
    fontWeight: '300',
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 40,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  shakeScreenIcon: {
    fontSize: 80,
    marginBottom: 48,
  },
  shakeProgressContainer: {
    width: '100%',
    alignItems: 'center',
  },
  shakeProgressBar: {
    width: '100%',
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 16,
  },
  shakeProgressFill: {
    height: '100%',
    backgroundColor: '#818CF8',
    borderRadius: 4,
  },
  shakeProgressText: {
    fontSize: 18,
    color: 'rgba(255, 255, 255, 0.5)',
    fontWeight: '500',
  },
  shakeCompleteContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  shakeCompleteText: {
    fontSize: 32,
    fontWeight: '300',
    color: '#4ADE80',
    letterSpacing: 1,
  },
  simpleDismissContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 40,
  },
  stopButton: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#818CF8',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#818CF8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  stopButtonText: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 2,
  },
  breathingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  breathingContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  breathingTimeText: {
    fontSize: 48,
    fontWeight: '200',
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 40,
  },
  breathingCircleContainer: {
    width: 220,
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 48,
  },
  breathingCircle: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(129, 140, 248, 0.25)',
    borderWidth: 2,
    borderColor: 'rgba(129, 140, 248, 0.6)',
  },
  breathingCircleInner: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  breathingPhaseLabel: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  breathingPhaseDuration: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.5)',
  },
  breathingCycleProgress: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  breathingCompleteContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  breathingGoodMorning: {
    fontSize: 36,
    fontWeight: '300',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  breathingCompleteLabel: {
    fontSize: 18,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  affirmationScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  affirmationContent: {
    width: '100%',
    alignItems: 'center',
  },
  affirmationPrompt: {
    fontSize: 18,
    fontWeight: '300',
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 32,
    letterSpacing: 0.5,
  },
  affirmationTargetContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 40,
    paddingHorizontal: 8,
  },
  affirmationCharRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  affirmationChar: {
    fontSize: 28,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.4)',
    letterSpacing: 1,
  },
  affirmationCharCorrect: {
    color: '#4ADE80',
  },
  affirmationCharWrong: {
    color: '#F87171',
  },
  affirmationInput: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    fontSize: 18,
    color: '#FFFFFF',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  affirmationCompleteContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  affirmationWellDone: {
    fontSize: 32,
    fontWeight: '300',
    color: '#4ADE80',
    letterSpacing: 1,
  },
  snoozeButton: {
    marginTop: 16,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  snoozeButtonText: {
    fontSize: 16,
    color: '#666666',
  },
  // Bedtime Modal Styles
  bedtimeModalContent: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    marginTop: 'auto',
  },
  bedtimeTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  bedtimeSubtitle: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 24,
  },
  saveBedtimeButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  saveBedtimeButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0D0D0D',
  },
  skipBedtimeButton: {
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  skipBedtimeButtonText: {
    fontSize: 16,
    color: '#666666',
  },
  // Sleep Insight Modal Styles
  insightOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  insightContent: {
    backgroundColor: '#1A1A1A',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    alignItems: 'center',
  },
  insightTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 20,
  },
  insightText: {
    fontSize: 16,
    color: '#999999',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 24,
  },
  insightHighlight: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  insightTime: {
    fontSize: 48,
    fontWeight: '300',
    color: '#FFFFFF',
    marginVertical: 20,
  },
  insightButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 32,
    marginTop: 12,
  },
  insightButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0D0D0D',
  },
  insightDismiss: {
    paddingVertical: 16,
    marginTop: 8,
  },
  insightDismissText: {
    fontSize: 16,
    color: '#666666',
  },
  // Settings Tab Styles
  settingsTabContent: {
    flex: 1,
    backgroundColor: '#0D0D0D',
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  settingsSectionHeader: {
    fontSize: 13,
    fontWeight: '600',
    color: '#818CF8',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 24,
    marginLeft: 4,
  },
  settingsCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    overflow: 'hidden',
  },
  settingsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  settingsItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  settingsItemLabelContainer: {
    flex: 1,
    marginRight: 12,
  },
  settingsItemLabel: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  settingsItemValue: {
    fontSize: 16,
    color: '#818CF8',
    fontWeight: '500',
  },
  settingsItemSubtext: {
    fontSize: 13,
    color: '#666666',
    marginTop: 2,
  },
  settingsItemChevron: {
    fontSize: 22,
    color: '#666666',
    fontWeight: '300',
  },
  settingsDivider: {
    height: 1,
    backgroundColor: '#2A2A2A',
    marginLeft: 16,
  },
  settingsBedtimePicker: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  settingsPickerLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  settingsFooter: {
    height: 100,
  },
  // Sleep Stats Modal Styles
  statsModalContent: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: 100,
    flex: 1,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  statsTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  statsCloseButton: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  statsScrollView: {
    flex: 1,
    padding: 20,
  },
  statsEmptyState: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  statsEmptyIcon: {
    fontSize: 64,
    marginBottom: 20,
  },
  statsEmptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  statsEmptyText: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
  },
  statsSection: {
    marginBottom: 24,
  },
  statsSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  weeklyChart: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    backgroundColor: '#0D0D0D',
    borderRadius: 16,
    padding: 16,
    height: 180,
  },
  chartBar: {
    alignItems: 'center',
    flex: 1,
  },
  chartDuration: {
    fontSize: 11,
    color: '#666666',
    marginBottom: 8,
  },
  chartBarContainer: {
    height: 120,
    width: 24,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  chartBarFill: {
    width: 20,
    borderRadius: 4,
    minHeight: 4,
  },
  chartBarToday: {
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  chartDay: {
    fontSize: 12,
    color: '#666666',
    marginTop: 8,
  },
  chartDayToday: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  statsCard: {
    backgroundColor: '#0D0D0D',
    borderRadius: 16,
    padding: 20,
  },
  statsMainStat: {
    alignItems: 'center',
    marginBottom: 20,
  },
  statsMainValue: {
    fontSize: 48,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  statsMainLabel: {
    fontSize: 16,
    color: '#666666',
    marginTop: 4,
  },
  statsSubStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: '#2A2A2A',
    paddingTop: 16,
  },
  statsSubStat: {
    alignItems: 'center',
  },
  statsSubLabel: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 4,
  },
  statsSubValue: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  statsBestWorst: {
    flexDirection: 'row',
    gap: 12,
  },
  statsBWCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
  },
  statsBestCard: {
    backgroundColor: 'rgba(99, 179, 237, 0.12)',
  },
  statsWorstCard: {
    backgroundColor: 'rgba(129, 140, 248, 0.12)',
  },
  statsBWIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  statsBWLabel: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 4,
  },
  statsBWValue: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  statsBWDate: {
    fontSize: 12,
    color: '#666666',
  },
  statsTotalNights: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
  },
  insightsContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  insightsTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 24,
  },
  insightsCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  insightsCardLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9999AA',
    marginBottom: 12,
  },
  insightsCardValue: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  insightsChart: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 120,
  },
  insightsBarCol: {
    alignItems: 'center',
    flex: 1,
  },
  insightsBarTrack: {
    width: 20,
    height: 100,
    backgroundColor: '#2A2A2A',
    borderRadius: 10,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  insightsBar: {
    width: '100%',
    backgroundColor: '#818CF8',
    borderRadius: 10,
  },
  insightsBarLabel: {
    fontSize: 12,
    color: '#9999AA',
    marginTop: 6,
  },
  insightsStatsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  insightsStatBox: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
  },
  insightsStatValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  insightsStatLabel: {
    fontSize: 13,
    color: '#9999AA',
  },
  insightsTipCard: {
    borderWidth: 1,
    borderColor: '#818CF8',
    marginBottom: 40,
  },
  insightsTipLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#818CF8',
    marginBottom: 6,
  },
  insightsTipText: {
    fontSize: 15,
    color: '#FFFFFF',
    lineHeight: 22,
  },
});
